# Generated by Django 3.1.5 on 2021-10-17 07:58

from django.db import migrations, models
import music_room_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=music_room_app.models.gen_unique_code, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
